### ISSUE TITLE
btapp.on('add:add' function(add){add.torrnet} not works

### ISSUE THREAD

**Issue by arestov** [bittorrenttorque/btapp#5]
``` javascript
var btapp = new Btapp();

btapp.on('add:add', function(add){
    console.log( typeof add.torrent ) 
};
//undefined

```

so add.torrent({...}) no works, but

``` javascript
var btapp = new Btapp();

btapp.on('add:add', function(add){
    setTimeout(function() {
        add.torrent({...})
    });
};
```

works fine

**Comment by pwmckenna** [comment]
uh oh...this was an unintended consequence of making the backbone tree creation asynchronous (which was to fix an issue that i've solved on the client side instead). pushing a fix now to btapp.js...you'll have to update your submodule if you're doing it that way.
